// Code generated by truss.
// Rerunning truss will overwrite this file.
// DO NOT EDIT!

package handlers

import (
	pb "github.com/hasAdamr/truss-metrics-datadog/metrics-service"
)

// Fast implements Service.
func Fast() (*pb.Empty, error) {
	request := pb.Empty{}
	return &request, nil
}

// Slow implements Service.
func Slow() (*pb.Empty, error) {
	request := pb.Empty{}
	return &request, nil
}

// RandomError implements Service.
func RandomError() (*pb.Empty, error) {
	request := pb.Empty{}
	return &request, nil
}
