// Code generated by truss.
// Rerunning truss will overwrite this file.
// DO NOT EDIT!

// Package grpc provides a gRPC client for the Metrics service.
package grpc

import (
	"github.com/pkg/errors"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/hasAdamr/truss-metrics-datadog/metrics-service"
	"github.com/hasAdamr/truss-metrics-datadog/metrics-service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.MetricsServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var fastEndpoint endpoint.Endpoint
	{
		fastEndpoint = grpctransport.NewClient(
			conn,
			"metrics.Metrics",
			"Fast",
			EncodeGRPCFastRequest,
			DecodeGRPCFastResponse,
			pb.Empty{},
			clientOptions...,
		).Endpoint()
	}

	var slowEndpoint endpoint.Endpoint
	{
		slowEndpoint = grpctransport.NewClient(
			conn,
			"metrics.Metrics",
			"Slow",
			EncodeGRPCSlowRequest,
			DecodeGRPCSlowResponse,
			pb.Empty{},
			clientOptions...,
		).Endpoint()
	}

	var randomerrorEndpoint endpoint.Endpoint
	{
		randomerrorEndpoint = grpctransport.NewClient(
			conn,
			"metrics.Metrics",
			"RandomError",
			EncodeGRPCRandomErrorRequest,
			DecodeGRPCRandomErrorResponse,
			pb.Empty{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		FastEndpoint:        fastEndpoint,
		SlowEndpoint:        slowEndpoint,
		RandomErrorEndpoint: randomerrorEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCFastResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC fast reply to a user-domain fast response. Primarily useful in a client.
func DecodeGRPCFastResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.Empty)
	return reply, nil
}

// DecodeGRPCSlowResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC slow reply to a user-domain slow response. Primarily useful in a client.
func DecodeGRPCSlowResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.Empty)
	return reply, nil
}

// DecodeGRPCRandomErrorResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC randomerror reply to a user-domain randomerror response. Primarily useful in a client.
func DecodeGRPCRandomErrorResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.Empty)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCFastRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain fast request to a gRPC fast request. Primarily useful in a client.
func EncodeGRPCFastRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.Empty)
	return req, nil
}

// EncodeGRPCSlowRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain slow request to a gRPC slow request. Primarily useful in a client.
func EncodeGRPCSlowRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.Empty)
	return req, nil
}

// EncodeGRPCRandomErrorRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain randomerror request to a gRPC randomerror request. Primarily useful in a client.
func EncodeGRPCRandomErrorRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.Empty)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.RequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
